import {
  type DatafnSchema,
  type DatafnFieldSchema,
  type DatafnRelationSchema,
  validateSchema,
  unwrapEnvelope,
  ensureBuiltinKv,
  ensureBuiltinTemporal,
  isNamespaced,
  resolveCapabilities,
  getCapabilityFields,
  RELATION_CAPABILITY_FIELD_DEFS,
  getRelationJoinTableName as resolveRelationJoinTableName,
} from "@datafn/core";

export type Dialect = "postgres" | "mysql" | "sqlite";

/**
 * Generate Drizzle ORM schema from a DataFn schema.
 */
export function generateDrizzleSchema(
  schemaInput: unknown,
  dialect: Dialect,
): string {
  const schema = ensureBuiltinTemporal(ensureBuiltinKv(unwrapEnvelope(validateSchema(schemaInput))));
  const lines: string[] = [];
  const usedImports = new Set<string>();
  const tableConstructor = getTableConstructor(dialect);
  const importPath = getImportPath(dialect);

  const tableExports: string[] = [];

  lines.push("// @ts-nocheck");
  lines.push("// Generated by @datafn/cli. DO NOT EDIT.");
  lines.push(`// Database: ${dialect}`);
  lines.push("");

  const resources = [...schema.resources].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  const relationFkColumnsByResource = buildRelationFkColumnsByResource(schema);
  const shareableResources: string[] = [];

  const nsEnabled = isNamespaced(schema);

  for (const resource of resources) {
    const tableName = resource.name;
    const varName = sanitizeVarName(tableName);
    tableExports.push(varName);
    usedImports.add(tableConstructor);

    const relationFkColumns = relationFkColumnsByResource.get(resource.name) ?? [];
    const declaredFieldNames = new Set(resource.fields.map((field) => field.name));
    const generatedRelationFields = relationFkColumns.flatMap((entry): DatafnFieldSchema[] => {
      const fieldsToAdd: DatafnFieldSchema[] = [];
      if (!declaredFieldNames.has(entry.field)) {
        fieldsToAdd.push({
          name: entry.field,
          type: "string",
          required: false,
          nullable: true,
        });
      }
      if (entry.resourceField && !declaredFieldNames.has(entry.resourceField)) {
        fieldsToAdd.push({
          name: entry.resourceField,
          type: "string",
          required: false,
          nullable: true,
        });
      }
      if (entry.pathField && !declaredFieldNames.has(entry.pathField)) {
        fieldsToAdd.push({
          name: entry.pathField,
          type: "string",
          required: false,
          nullable: true,
        });
      }
      return fieldsToAdd;
    });
    const generatedFieldNames = new Set<string>();
    const fields = ensureIdField([
      ...resource.fields,
      ...generatedRelationFields.filter((field) => {
        if (declaredFieldNames.has(field.name) || generatedFieldNames.has(field.name)) {
          return false;
        }
        generatedFieldNames.add(field.name);
        return true;
      }),
    ]).sort((a, b) =>
      a.name.localeCompare(b.name),
    );
    const resolvedCapabilities = resolveCapabilities(
      schema.capabilities,
      resource.capabilities,
    );
    const hasShareable = resolvedCapabilities.some(
      (capability) =>
        typeof capability === "object" &&
        capability !== null &&
        "shareable" in capability,
    );
    if (hasShareable) {
      shareableResources.push(resource.name);
    }

    const resolvedCapabilityFields = getCapabilityFields(resolvedCapabilities);
    const capabilityFieldNames = new Set(
      resolvedCapabilityFields.map((field) => field.name),
    );
    const capabilityFields = resolvedCapabilityFields.filter(
      (field) => !fields.some((userField) => userField.name === field.name),
    );
    if (hasShareable) {
      // Compatibility fallback: older core builds may not inject `visibility` yet.
      capabilityFieldNames.add("visibility");
      if (!fields.some((field) => field.name === "visibility")) {
        capabilityFields.push({
          name: "visibility",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
          default: null,
        });
      }
    }

    const hasBaseIndices =
      resource.indices &&
      typeof resource.indices === "object" &&
      !Array.isArray(resource.indices) &&
      "base" in resource.indices &&
      resource.indices.base?.length;
    const hasExplicitIdField = fields.some((field) => field.name === "id");
    const relationForeignKeys = relationFkColumns
      .filter((entry) => shouldEmitForeignKey(schema, entry.relation))
      .filter((entry) => Boolean(entry.targetResource));

    lines.push(`export const ${varName} = ${tableConstructor}("${tableName}", {`);

    // Add __ns column when namespaced (alphabetical: __ns sorts before all alpha fields)
    if (nsEnabled) {
      usedImports.add("text");
      lines.push(`  __ns: text("__ns").notNull(),`);
    }

    for (const field of fields) {
      const colDef = capabilityFieldNames.has(field.name)
        ? buildCapabilityColumnDefinition(field, dialect, usedImports)
        : buildColumnDefinition(field, dialect, usedImports, nsEnabled);
      lines.push(`  ${renderTsObjectKey(field.name)}: ${colDef},`);
    }
    for (const field of capabilityFields) {
      const colDef = buildCapabilityColumnDefinition(field, dialect, usedImports);
      lines.push(`  ${renderTsObjectKey(field.name)}: ${colDef},`);
    }

    const needsIndexCallback =
      hasBaseIndices ||
      nsEnabled ||
      hasShareable ||
      relationFkColumns.length > 0 ||
      relationForeignKeys.length > 0;

    if (needsIndexCallback) {
      usedImports.add("index");
      lines.push(`}, (table) => [`);
      if (nsEnabled) {
        if (hasExplicitIdField) {
          usedImports.add("primaryKey");
          lines.push(`  primaryKey({ columns: [table.__ns, ${tableAccessor("id")}] }),`);
        }
        lines.push(`  index("idx_${tableName}___ns").on(table.__ns),`);
      }
      if (hasBaseIndices) {
        const baseIndices = (resource.indices as { base?: string[] }).base!;
        for (const idxField of baseIndices) {
          lines.push(
            `  index("${tableName}_${camelToSnake(idxField)}_idx").on(${tableAccessor(idxField)}),`,
          );
        }
      }
      if (hasShareable) {
        // PERF-001: optimize private/shared query paths.
        lines.push(`  index("idx_${tableName}_visibility").on(${tableAccessor("visibility")}),`);
        lines.push(
          `  index("idx_${tableName}_created_by_visibility").on(${tableAccessor("createdBy")}, ${tableAccessor("visibility")}),`,
        );
      }
      for (const entry of relationFkColumns) {
        const indexColumns = relationIndexColumns(entry, nsEnabled);
        lines.push(`  index("${tableName}_${camelToSnake(entry.field)}_rel_idx").on(${indexColumns}),`);
        if (entry.pathField) {
          const pathColumns = nsEnabled
            ? joinIndexColumnList(["__ns", entry.pathField])
            : joinIndexColumnList([entry.pathField]);
          lines.push(`  index("${tableName}_${camelToSnake(entry.pathField)}_rel_idx").on(${pathColumns}),`);
        }
      }
      for (const entry of relationForeignKeys) {
        usedImports.add("foreignKey");
        lines.push(`  ${buildForeignKeyDefinition(entry, nsEnabled)},`);
      }
      lines.push(`]);`);
    } else {
      lines.push(`});`);
    }
    lines.push("");
  }

  if (shareableResources.length > 0) {
    const permissionsTableName = "__datafn_permissions_global";
    const membershipsTableName = "__datafn_principal_memberships";
    const hierarchyTableName = "__datafn_principal_hierarchy";

    const permissionsVarName = sanitizeVarName(permissionsTableName);
    const membershipsVarName = sanitizeVarName(membershipsTableName);
    const hierarchyVarName = sanitizeVarName(hierarchyTableName);

    tableExports.push(permissionsVarName, membershipsVarName, hierarchyVarName);

    usedImports.add(tableConstructor);
    usedImports.add("text");
    usedImports.add("primaryKey");
    usedImports.add("uniqueIndex");
    usedImports.add("index");

    // SQLite has no bigint — use integer instead
    const tsCol = dialect === "sqlite"
      ? (name: string) => { usedImports.add("integer"); return `integer("${name}")`; }
      : (name: string) => { usedImports.add("bigint"); return `bigint("${name}", { mode: "number" })`; };

    lines.push(
      `export const ${permissionsVarName} = ${tableConstructor}("${permissionsTableName}", {`,
    );
    if (nsEnabled) {
      lines.push(`  __ns: text("__ns"),`);
    }
    lines.push(`  id: text("id").notNull(),`);
    lines.push(`  resourceType: text("resource_type").notNull(),`);
    lines.push(`  resourceNs: text("resource_ns").notNull(),`);
    lines.push(`  resourceId: text("resource_id"),`);
    lines.push(`  principalId: text("principal_id").notNull(),`);
    lines.push(`  level: text("level").notNull(),`);
    lines.push(`  grantKind: text("grant_kind").notNull(),`);
    lines.push(`  sourceRef: text("source_ref"),`);
    lines.push(`  grantedBy: text("granted_by").notNull(),`);
    lines.push(`  grantedAt: ${tsCol("granted_at")}.notNull(),`);
    lines.push(`  revokedAt: ${tsCol("revoked_at")},`);
    lines.push(`}, (table) => [`);
    lines.push(`  primaryKey({ columns: [table.id] }),`);
    lines.push(
      `  uniqueIndex("${permissionsTableName}_resource_record_idx").on(table.resourceType, table.resourceNs, table.resourceId, table.principalId),`,
    );
    lines.push(
      `  uniqueIndex("${permissionsTableName}_scope_idx").on(table.resourceType, table.resourceNs, table.principalId, table.grantKind),`,
    );
    lines.push(`  index("idx_perm_principal").on(table.principalId),`);
    lines.push(
      `  index("idx_perm_resource_ns_principal").on(table.resourceNs, table.principalId),`,
    );
    lines.push(
      `  index("idx_perm_resource_lookup").on(table.resourceType, table.resourceNs, table.resourceId),`,
    );
    lines.push(
      `  index("idx_perm_active_lookup").on(table.resourceType, table.resourceNs, table.principalId, table.revokedAt),`,
    );
    lines.push(`]);`);
    lines.push("");

    lines.push(
      `export const ${membershipsVarName} = ${tableConstructor}("${membershipsTableName}", {`,
    );
    if (nsEnabled) {
      lines.push(`  __ns: text("__ns"),`);
    }
    lines.push(`  id: text("id").notNull(),`);
    lines.push(`  namespace: text("namespace").notNull(),`);
    lines.push(`  actorId: text("actor_id").notNull(),`);
    lines.push(`  principalId: text("principal_id").notNull(),`);
    lines.push(`  grantedAt: ${tsCol("granted_at")}.notNull(),`);
    lines.push(`  revokedAt: ${tsCol("revoked_at")},`);
    lines.push(`}, (table) => [`);
    lines.push(`  primaryKey({ columns: [table.id] }),`);
    lines.push(
      `  uniqueIndex("${membershipsTableName}_namespace_actor_principal_idx").on(table.namespace, table.actorId, table.principalId),`,
    );
    lines.push(`  index("idx_membership_actor").on(table.namespace, table.actorId),`);
    lines.push(
      `  index("idx_membership_principal").on(table.namespace, table.principalId),`,
    );
    lines.push(
      `  index("idx_membership_active").on(table.namespace, table.actorId, table.revokedAt),`,
    );
    lines.push(`]);`);
    lines.push("");

    lines.push(
      `export const ${hierarchyVarName} = ${tableConstructor}("${hierarchyTableName}", {`,
    );
    if (nsEnabled) {
      lines.push(`  __ns: text("__ns"),`);
    }
    lines.push(`  id: text("id").notNull(),`);
    lines.push(`  namespace: text("namespace").notNull(),`);
    lines.push(`  principalId: text("principal_id").notNull(),`);
    lines.push(`  parentPrincipalId: text("parent_principal_id").notNull(),`);
    lines.push(`  createdAt: ${tsCol("created_at")}.notNull(),`);
    lines.push(`  revokedAt: ${tsCol("revoked_at")},`);
    lines.push(`}, (table) => [`);
    lines.push(`  primaryKey({ columns: [table.id] }),`);
    lines.push(
      `  uniqueIndex("${hierarchyTableName}_namespace_principal_parent_idx").on(table.namespace, table.principalId, table.parentPrincipalId),`,
    );
    lines.push(
      `  index("idx_hierarchy_principal").on(table.namespace, table.principalId),`,
    );
    lines.push(
      `  index("idx_hierarchy_parent").on(table.namespace, table.parentPrincipalId),`,
    );
    lines.push(
      `  index("idx_hierarchy_active").on(table.namespace, table.principalId, table.revokedAt),`,
    );
    lines.push(`]);`);
    lines.push("");
  }

  emitInternalTables(lines, tableExports, usedImports, tableConstructor, dialect);

  const relations = schema.relations ?? [];
  const sortedRelations = [...relations]
    .filter((rel) => rel.type === "many-many")
    .sort((a, b) => {
      const aName = resolveRelationJoinTableName(a);
      const bName = resolveRelationJoinTableName(b);
      return aName.localeCompare(bName);
    });

  for (const rel of sortedRelations) {
    const jtName = resolveRelationJoinTableName(rel);
    const varName = sanitizeVarName(jtName);
    tableExports.push(varName);
    usedImports.add(tableConstructor);

    const fromCol = rel.joinColumns?.from ?? "from";
    const toCol = rel.joinColumns?.to ?? "to";
    const fromResources = endpointListOf(rel.from);
    const toResources = endpointListOf(rel.to);
    const hasPolymorphicFrom = fromResources.length > 1;
    const hasPolymorphicTo = toResources.length > 1;
    const metadataFieldNames = new Set(
      (rel.metadata ?? []).map((field) => field.name),
    );
    const emitManyManyFromForeignKey = shouldEmitForeignKey(schema, rel) && !hasPolymorphicFrom;
    const emitManyManyToForeignKey = shouldEmitForeignKey(schema, rel) && !hasPolymorphicTo;

    lines.push(`export const ${varName} = ${tableConstructor}("${jtName}", {`);

    const joinFields: Array<{ name: string; def: string }> = [];

    // Add __ns column for join tables when namespaced
    if (nsEnabled) {
      usedImports.add("text");
      joinFields.push({
        name: "__ns",
        def: `text("__ns").notNull()`,
      });
    }

    joinFields.push(
      {
        name: fromCol,
        def: buildSimpleColumn(fromCol, "string", dialect, usedImports, true),
      },
      {
        name: "id",
        def: buildSimpleColumn(
          "id",
          "string",
          dialect,
          usedImports,
          nsEnabled, // notNull when namespaced (PK defined in callback)
          !nsEnabled, // primaryKey only when not namespaced
        ),
      },
      {
        name: toCol,
        def: buildSimpleColumn(toCol, "string", dialect, usedImports, true),
      },
    );

    if (hasPolymorphicFrom && !metadataFieldNames.has("fromResource")) {
      usedImports.add("text");
      joinFields.push({
        name: "fromResource",
        def: `text("from_resource").notNull()`,
      });
    }
    if (hasPolymorphicTo && !metadataFieldNames.has("toResource")) {
      usedImports.add("text");
      joinFields.push({
        name: "toResource",
        def: `text("to_resource").notNull()`,
      });
    }

    if (rel.metadata) {
      for (const meta of rel.metadata) {
        const isDeclaredDiscriminator =
          (meta.name === "fromResource" && hasPolymorphicFrom) ||
          (meta.name === "toResource" && hasPolymorphicTo);
        joinFields.push({
          name: meta.name,
          def: buildSimpleColumn(
            meta.name,
            meta.type,
            dialect,
            usedImports,
            isDeclaredDiscriminator,
          ),
        });
      }
    }

    // JCG-001: Inject relation capability columns for opted-in many-many relations
    if (rel.capabilities && rel.capabilities.length > 0) {
      const canonicalCaps = (["timestamps", "audit"] as const).filter(
        (cap) => (rel.capabilities as string[]).includes(cap),
      );
      for (const cap of canonicalCaps) {
        for (const fieldDef of RELATION_CAPABILITY_FIELD_DEFS[cap]) {
          const snakeName = camelToSnake(fieldDef.name);
          const { call, importName } = fieldDef.type === "date"
            ? getEpochColumnType(dialect, snakeName)
            : getColumnType(fieldDef.type, dialect, snakeName);
          usedImports.add(importName);
          joinFields.push({
            name: fieldDef.name,
            def: call,
          });
        }
      }
    }

    joinFields.sort((a, b) => a.name.localeCompare(b.name));

    for (const jf of joinFields) {
      lines.push(`  ${renderTsObjectKey(jf.name)}: ${jf.def},`);
    }

    const fromSnake = camelToSnake(fromCol);
    const toSnake = camelToSnake(toCol);
    const identityColumns = rel.identityMetadata ?? [];
    usedImports.add("uniqueIndex");
    usedImports.add("index");
    lines.push(`}, (table) => [`);
    if (nsEnabled) {
      usedImports.add("primaryKey");
      lines.push(`  primaryKey({ columns: [table.__ns, table.id] }),`);
      lines.push(`  index("idx_${jtName}___ns").on(table.__ns),`);
    }
    const uniqueColumns = nsEnabled
      ? joinIndexColumnList(["__ns", hasPolymorphicFrom ? "fromResource" : undefined, fromCol, hasPolymorphicTo ? "toResource" : undefined, toCol, ...identityColumns])
      : joinIndexColumnList([hasPolymorphicFrom ? "fromResource" : undefined, fromCol, hasPolymorphicTo ? "toResource" : undefined, toCol, ...identityColumns]);
    lines.push(`  uniqueIndex("${jtName}_${fromSnake}_${toSnake}_idx").on(${uniqueColumns}),`);
    const fromIndexColumns = nsEnabled
      ? joinIndexColumnList(["__ns", hasPolymorphicFrom ? "fromResource" : undefined, fromCol])
      : joinIndexColumnList([hasPolymorphicFrom ? "fromResource" : undefined, fromCol]);
    const toIndexColumns = nsEnabled
      ? joinIndexColumnList(["__ns", hasPolymorphicTo ? "toResource" : undefined, toCol])
      : joinIndexColumnList([hasPolymorphicTo ? "toResource" : undefined, toCol]);
    lines.push(`  index("${jtName}_${fromSnake}_idx").on(${fromIndexColumns}),`);
    lines.push(`  index("${jtName}_${toSnake}_idx").on(${toIndexColumns}),`);
    if (emitManyManyFromForeignKey) {
      usedImports.add("foreignKey");
      lines.push(`  ${buildJoinForeignKeyDefinition(fromCol, fromResources[0], "from", rel, nsEnabled)},`);
    }
    if (emitManyManyToForeignKey) {
      usedImports.add("foreignKey");
      lines.push(`  ${buildJoinForeignKeyDefinition(toCol, toResources[0], "to", rel, nsEnabled)},`);
    }
    lines.push(`]);`);
    lines.push("");
  }

  tableExports.sort();
  lines.push(`export const schema = { ${tableExports.join(", ")} };`);
  lines.push("");

  const sortedImports = [...usedImports].sort();
  const importLine = `import { ${sortedImports.join(", ")} } from "${importPath}";`;

  lines.splice(2, 0, importLine);

  return lines.join("\n");
}

function getTableConstructor(dialect: Dialect): string {
  switch (dialect) {
    case "postgres":
      return "pgTable";
    case "mysql":
      return "mysqlTable";
    case "sqlite":
      return "sqliteTable";
  }
}

function getImportPath(dialect: Dialect): string {
  switch (dialect) {
    case "postgres":
      return "drizzle-orm/pg-core";
    case "mysql":
      return "drizzle-orm/mysql-core";
    case "sqlite":
      return "drizzle-orm/sqlite-core";
  }
}

export function camelToSnake(str: string): string {
  return str
    .replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function sanitizeVarName(name: string): string {
  const sanitized = name.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(sanitized) ? sanitized : `_${sanitized}`;
}

function buildColumnDefinition(
  field: DatafnFieldSchema,
  dialect: Dialect,
  usedImports: Set<string>,
  isNamespaced = false,
): string {
  const snakeName = camelToSnake(field.name);
  const { call, importName } = field.type === "date"
    ? getEpochColumnType(dialect, snakeName)
    : getColumnType(field.type, dialect, snakeName);
  usedImports.add(importName);

  let def = call;

  if (field.name === "id") {
    // In namespaced mode, composite PK (__ns, id) is defined in the table callback
    if (!isNamespaced) {
      def += ".primaryKey()";
    } else {
      def += ".notNull()";
    }
  } else {
    if (field.required && field.nullable !== true) def += ".notNull()";
    if (field.unique === true) def += ".unique()";
  }

  if (field.default !== undefined) {
    def += `.default(${JSON.stringify(field.default)})`;
  }

  return def;
}

function renderTsObjectKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function ensureIdField(fields: readonly DatafnFieldSchema[]): DatafnFieldSchema[] {
  if (fields.some((field) => field.name === "id")) {
    return [...fields];
  }

  return [
    { name: "id", type: "string", required: true, readonly: true },
    ...fields,
  ];
}

function tableAccessor(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? `table.${name}`
    : `table[${JSON.stringify(name)}]`;
}

function buildSimpleColumn(
  fieldName: string,
  fieldType: string,
  dialect: Dialect,
  usedImports: Set<string>,
  notNull: boolean,
  primaryKey = false,
): string {
  const snakeName = camelToSnake(fieldName);
  const { call, importName } = getColumnType(fieldType, dialect, snakeName);
  usedImports.add(importName);

  let def = call;

  if (primaryKey) {
    def += ".primaryKey()";
  } else if (notNull) {
    def += ".notNull()";
  }

  return def;
}

function buildCapabilityColumnDefinition(
  field: DatafnFieldSchema,
  dialect: Dialect,
  usedImports: Set<string>,
): string {
  const snakeName = camelToSnake(field.name);
  const { call, importName } = getColumnType(field.type, dialect, snakeName);
  usedImports.add(importName);

  let def = call;

  if (field.name === "createdAt" || field.name === "updatedAt") {
    def += ".notNull()";
  } else if (field.name === "isArchived") {
    def += ".notNull().default(false)";
  }

  return def;
}

function emitInternalTables(
  lines: string[],
  tableExports: string[],
  usedImports: Set<string>,
  tableConstructor: string,
  dialect: Dialect,
): void {
  const tables = [
    {
      tableName: "__datafn_changes",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "server_seq", sqlName: "server_seq", type: "integer" },
        { property: "resource", sqlName: "resource", type: "text" },
        { property: "record_id", sqlName: "record_id", type: "text" },
        { property: "op", sqlName: "op", type: "text" },
        { property: "record", sqlName: "record", type: "text" },
        { property: "created_at", sqlName: "created_at", type: "text" },
      ],
      indexes: [
        'index("__datafn_changes_namespace_server_seq_idx").on(table.namespace, table.server_seq)',
      ],
    },
    {
      tableName: "__datafn_idempotency",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "client_id", sqlName: "client_id", type: "text" },
        { property: "mutation_id", sqlName: "mutation_id", type: "text" },
        { property: "result", sqlName: "result", type: "text" },
        { property: "created_at", sqlName: "created_at", type: "text" },
      ],
      indexes: [
        'index("__datafn_idempotency_namespace_client_mutation_idx").on(table.namespace, table.client_id, table.mutation_id)',
      ],
    },
    {
      tableName: "__datafn_meta",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "next_server_seq", sqlName: "next_server_seq", type: "integer" },
      ],
      indexes: [] as string[],
    },
    {
      tableName: "__datafn_seed",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "seed_id", sqlName: "seed_id", type: "text" },
        { property: "status", sqlName: "status", type: "text" },
        { property: "created_at", sqlName: "created_at", type: "text" },
      ],
      indexes: [
        'index("__datafn_seed_namespace_seed_idx").on(table.namespace, table.seed_id)',
      ],
    },
  ];

  usedImports.add(tableConstructor);
  usedImports.add("text");

  for (const table of tables) {
    const varName = sanitizeVarName(table.tableName);
    tableExports.push(varName);

    lines.push(`export const ${varName} = ${tableConstructor}("${table.tableName}", {`);
    for (const column of table.columns) {
      let def: string;
      if (column.type === "integer") {
        const { call, importName } = getInternalIntegerColumnType(dialect, column.sqlName);
        usedImports.add(importName);
        def = call;
      } else {
        def = `text("${column.sqlName}")`;
      }
      if (column.primaryKey) {
        def += ".primaryKey()";
      }
      lines.push(`  ${column.property}: ${def},`);
    }

    if (table.indexes.length > 0) {
      usedImports.add("index");
      lines.push(`}, (table) => [`);
      for (const indexDef of table.indexes) {
        lines.push(`  ${indexDef},`);
      }
      lines.push(`]);`);
    } else {
      lines.push(`});`);
    }
    lines.push("");
  }
}

function getColumnType(
  fieldType: string,
  dialect: Dialect,
  sqlName: string,
): { call: string; importName: string } {
  if (dialect === "postgres") {
    switch (fieldType) {
      case "string":
      case "file":
        return { call: `text("${sqlName}")`, importName: "text" };
      case "number":
        return { call: `numeric("${sqlName}")`, importName: "numeric" };
      case "boolean":
        return { call: `boolean("${sqlName}")`, importName: "boolean" };
      case "date":
        return getEpochColumnType(dialect, sqlName);
      case "object":
      case "array":
      case "json":
        return { call: `jsonb("${sqlName}")`, importName: "jsonb" };
      default:
        return { call: `text("${sqlName}")`, importName: "text" };
    }
  }

  if (dialect === "mysql") {
    switch (fieldType) {
      case "string":
      case "file":
        return { call: `text("${sqlName}")`, importName: "text" };
      case "number":
        return { call: `int("${sqlName}")`, importName: "int" };
      case "boolean":
        return { call: `boolean("${sqlName}")`, importName: "boolean" };
      case "date":
        return {
          call: `bigint("${sqlName}", { mode: "number" })`,
          importName: "bigint",
        };
      case "object":
      case "array":
      case "json":
        return { call: `json("${sqlName}")`, importName: "json" };
      default:
        return { call: `text("${sqlName}")`, importName: "text" };
    }
  }

  switch (fieldType) {
    case "string":
    case "file":
    case "object":
    case "array":
    case "json":
      return { call: `text("${sqlName}")`, importName: "text" };
    case "number":
    case "boolean":
    case "date":
      return { call: `integer("${sqlName}")`, importName: "integer" };
    default:
      return { call: `text("${sqlName}")`, importName: "text" };
  }
}

function getInternalIntegerColumnType(
  dialect: Dialect,
  sqlName: string,
): { call: string; importName: string } {
  if (dialect === "mysql") {
    return { call: `int("${sqlName}")`, importName: "int" };
  }
  return { call: `integer("${sqlName}")`, importName: "integer" };
}

function getEpochColumnType(
  dialect: Dialect,
  sqlName: string,
): { call: string; importName: string } {
  if (dialect === "sqlite") {
    return { call: `integer("${sqlName}")`, importName: "integer" };
  }
  return { call: `bigint("${sqlName}", { mode: "number" })`, importName: "bigint" };
}

type RelationFkColumn = {
  resource: string;
  field: string;
  relation: DatafnRelationSchema;
  targetResource?: string;
  targetSide: "from" | "to";
  resourceField?: string;
  pathField?: string;
};

function endpointListOf(endpoint: string | readonly string[]): string[] {
  return typeof endpoint === "string" ? [endpoint] : [...endpoint];
}

function firstEndpointOf(endpoint: string | readonly string[]): string {
  return typeof endpoint === "string" ? endpoint : endpoint[0];
}

function resolveRelationIntegrity(
  schema: DatafnSchema,
  relation: DatafnRelationSchema,
): string {
  return relation.integrity ?? schema.relationIntegrity ?? "application";
}

function shouldEmitForeignKey(
  schema: DatafnSchema,
  relation: DatafnRelationSchema,
): boolean {
  const mode = resolveRelationIntegrity(schema, relation);
  return mode === "database";
}

function fkFieldForOneMany(relation: DatafnRelationSchema): string {
  return relation.fkField || relation.foreignKey || relation.inverse || `${firstEndpointOf(relation.from)}Id`;
}

function htreeFkField(relation: DatafnRelationSchema): string {
  return relation.fkField || relation.foreignKey || relation.inverse || "parentId";
}

function htreePathField(relation: DatafnRelationSchema): string {
  return relation.pathField || "parentPath";
}

function fkResourceFieldForRelation(
  relation: DatafnRelationSchema,
  side: "from" | "to",
): string {
  if (relation.fkResourceField) return relation.fkResourceField;
  if (relation.type === "htree") {
    return `${htreeFkField(relation).replace(/Id$/, "")}Resource`;
  }
  const base = side === "to"
    ? (relation.relation || "target")
    : (relation.inverse || relation.relation || "source");
  return `${base.replace(/Id$/, "")}Resource`;
}

function buildRelationFkColumnsByResource(
  schema: DatafnSchema,
): Map<string, RelationFkColumn[]> {
  const byResource = new Map<string, RelationFkColumn[]>();
  const add = (entry: RelationFkColumn) => {
    const entries = byResource.get(entry.resource) ?? [];
    if (!entries.some((existing) => existing.field === entry.field && existing.relation === entry.relation)) {
      entries.push(entry);
    }
    byResource.set(entry.resource, entries);
  };

  for (const relation of schema.relations ?? []) {
    if (relation.type === "many-one") {
      const toResources = endpointListOf(relation.to);
      const targetResource = toResources.length === 1 ? toResources[0] : undefined;
      const resourceField = toResources.length > 1
        ? fkResourceFieldForRelation(relation, "to")
        : undefined;
      for (const resource of endpointListOf(relation.from)) {
        add({
          resource,
          field: relation.fkField || relation.foreignKey || `${relation.relation ?? toResources[0]}Id`,
          relation,
          targetResource,
          targetSide: "to",
          resourceField,
        });
      }
    } else if (relation.type === "one-many") {
      const fromResources = endpointListOf(relation.from);
      const targetResource = fromResources.length === 1 ? fromResources[0] : undefined;
      const resourceField = fromResources.length > 1
        ? fkResourceFieldForRelation(relation, "from")
        : undefined;
      for (const resource of endpointListOf(relation.to)) {
        add({
          resource,
          field: fkFieldForOneMany(relation),
          relation,
          targetResource,
          targetSide: "from",
          resourceField,
        });
      }
    } else if (relation.type === "htree") {
      const fromResources = endpointListOf(relation.from);
      const targetResource = fromResources.length === 1 ? fromResources[0] : undefined;
      const resourceField = fromResources.length > 1
        ? fkResourceFieldForRelation(relation, "from")
        : undefined;
      for (const resource of endpointListOf(relation.to)) {
        add({
          resource,
          field: htreeFkField(relation),
          relation,
          targetResource,
          targetSide: "from",
          resourceField,
          pathField: htreePathField(relation),
        });
      }
    }
  }

  return byResource;
}

function joinIndexColumnList(columns: Array<string | undefined>): string {
  return columns
    .filter((column): column is string => Boolean(column))
    .map((column) => tableAccessor(column))
    .join(", ");
}

function relationIndexColumns(entry: RelationFkColumn, namespaced: boolean): string {
  return namespaced
    ? joinIndexColumnList(["__ns", entry.resourceField, entry.field])
    : joinIndexColumnList([entry.resourceField, entry.field]);
}

function resolveDeletePolicy(
  relation: DatafnRelationSchema,
  side: "from" | "to",
): string | undefined {
  const policy = relation.onDelete;
  if (typeof policy === "string") return policy;
  if (policy && typeof policy === "object") return policy[side];
  return undefined;
}

function relationForeignKeyDeleteAction(
  relation: DatafnRelationSchema,
  side: "from" | "to",
): string | undefined {
  const policy = resolveDeletePolicy(relation, side);
  if (policy === "cascade") return "cascade";
  if (policy === "restrict") return "restrict";
  if (policy === "setNull" || policy === "detach") return "set null";
  return undefined;
}

function joinForeignKeyDeleteAction(
  relation: DatafnRelationSchema,
  side: "from" | "to",
): string | undefined {
  const policy = resolveDeletePolicy(relation, side);
  if (policy === "restrict") return "restrict";
  if (policy === "cascade" || policy === "detach" || policy === "setNull") return "cascade";
  return undefined;
}

function buildForeignKeyDefinition(entry: RelationFkColumn, namespaced: boolean): string {
  const targetTable = sanitizeVarName(entry.targetResource!);
  const columns = namespaced
    ? `[table.__ns, ${tableAccessor(entry.field)}]`
    : `[${tableAccessor(entry.field)}]`;
  const foreignColumns = namespaced
    ? `[${targetTable}.__ns, ${targetTable}.id]`
    : `[${targetTable}.id]`;
  const action = relationForeignKeyDeleteAction(entry.relation, entry.targetSide);
  const definition = `foreignKey({ columns: ${columns}, foreignColumns: ${foreignColumns} })`;
  const databaseAction = namespaced && action === "set null" ? undefined : action;
  return databaseAction ? `${definition}.onDelete(${JSON.stringify(databaseAction)})` : definition;
}

function buildJoinForeignKeyDefinition(
  column: string,
  resource: string,
  side: "from" | "to",
  relation: DatafnRelationSchema,
  namespaced: boolean,
): string {
  const targetTable = sanitizeVarName(resource);
  const columns = namespaced
    ? `[table.__ns, ${tableAccessor(column)}]`
    : `[${tableAccessor(column)}]`;
  const foreignColumns = namespaced
    ? `[${targetTable}.__ns, ${targetTable}.id]`
    : `[${targetTable}.id]`;
  const action = joinForeignKeyDeleteAction(relation, side);
  const definition = `foreignKey({ columns: ${columns}, foreignColumns: ${foreignColumns} })`;
  return action ? `${definition}.onDelete(${JSON.stringify(action)})` : definition;
}
