"""Python contract surface for the multi-package authfn platform."""

__version__ = "0.0.1"
__author__ = "21n"
__license__ = "MIT"

from .authfn import AuthFn, AuthFnProvider, create_authfn
from .config import get_plugin, get_plugin_config, normalize_config, resolve_runtime
from .http import create_authfn_openapi, create_authfn_routes
from .plugins.api_keys import ApiKeyPluginConfig, ApiKeyService
from .plugins.email_otp import EmailOtpPluginConfig, EmailOtpService
from .plugins.gateway_routing import (
    CanonicalGateway,
    CanonicalGatewayOptions,
    CanonicalRoutingConfig,
    GatewayCell,
    GatewayIdentity,
    IdentityPlacement,
    InMemoryIdentityPlacementDirectory,
    InMemoryRoutingReplayStore,
    RoutingKeyring,
    RoutingSigningKey,
    classify_route,
    create_cell_routing_middleware,
    move_identity_placement,
)
from .plugins.multi_region import (
    MultiRegionPluginConfig,
    MultiRegionRegionConfig,
    MultiRegionService,
)
from .plugins.placement_context import (
    PlacementBoundAuthContext,
    PlacementContextIssuer,
    PlacementContextVerifier,
    create_placement_context_issuer,
    create_placement_context_verifier,
)
from .plugins.social_oauth import (
    SocialOAuthPluginConfig,
    SocialOAuthService,
    SocialProviderConfig,
)
from .plugins.two_factor import TwoFactorPluginConfig, TwoFactorService
from .schema import AUTHFN_SCHEMA_VERSION, get_schema
from .types import (
    ApiKey,
    ApiKeyCreate,
    ApiKeyResponse,
    ApiKeyRevokedError,
    ApiKeySanitized,
    ApiKeySession,
    AuthFnConfig,
    AuthFnCookieConfig,
    AuthFnError,
    AuthFnEvent,
    AuthFnHookContext,
    AuthFnHooks,
    AuthFnObservabilityConfig,
    AuthFnPlugin,
    AuthFnPluginRuntimeContext,
    AuthFnRuntimeResolution,
    AuthFnRuntimeResolver,
    AuthFnSchemaConflictError,
    AuthFnSession,
    ConfigError,
    ConflictError,
    CsrfInvalidError,
    DeliveryFailedError,
    EmailNotVerifiedError,
    ExpiredCredentialsError,
    InternalError,
    InvalidCredentialsError,
    NotFoundError,
    NotImplementedAuthError,
    OAuthCallbackInvalidError,
    OAuthProviderUnsupportedError,
    OAuthStateInvalidError,
    OAuthStateReplayedError,
    OtpExpiredError,
    OtpInvalidError,
    OtpReplayedError,
    PlacementContextInvalidError,
    PlacementDirectoryUnavailableError,
    PlacementMovingError,
    PluginAbortedError,
    RateLimitedError,
    RedirectUriDisallowedError,
    RegionMismatchError,
    RegionNotFoundError,
    RoutingAssertionInvalidError,
    RoutingCellUnavailableError,
    SessionExpiredError,
    SessionRevokedError,
    TwoFactorInvalidCodeError,
    TwoFactorRequiredError,
    UnauthorizedError,
    ValidationError,
    authfn_api_key_plugin,
    authfn_email_otp_plugin,
    authfn_multi_region_plugin,
    authfn_password_plugin,
    authfn_social_oauth_plugin,
    authfn_two_factor_plugin,
)

__all__ = [
    "__version__",
    "__author__",
    "__license__",
    "AUTHFN_SCHEMA_VERSION",
    "AuthFn",
    "AuthFnProvider",
    "create_authfn",
    "create_authfn_openapi",
    "create_authfn_routes",
    "ApiKeyPluginConfig",
    "ApiKeyService",
    "EmailOtpPluginConfig",
    "EmailOtpService",
    "TwoFactorPluginConfig",
    "TwoFactorService",
    "MultiRegionPluginConfig",
    "MultiRegionRegionConfig",
    "MultiRegionService",
    "CanonicalGateway",
    "CanonicalGatewayOptions",
    "CanonicalRoutingConfig",
    "GatewayCell",
    "GatewayIdentity",
    "IdentityPlacement",
    "InMemoryIdentityPlacementDirectory",
    "InMemoryRoutingReplayStore",
    "RoutingKeyring",
    "RoutingSigningKey",
    "classify_route",
    "create_cell_routing_middleware",
    "move_identity_placement",
    "PlacementBoundAuthContext",
    "PlacementContextIssuer",
    "PlacementContextVerifier",
    "create_placement_context_issuer",
    "create_placement_context_verifier",
    "SocialOAuthPluginConfig",
    "SocialOAuthService",
    "SocialProviderConfig",
    "AuthFnConfig",
    "AuthFnCookieConfig",
    "AuthFnEvent",
    "AuthFnObservabilityConfig",
    "AuthFnRuntimeResolution",
    "AuthFnRuntimeResolver",
    "normalize_config",
    "resolve_runtime",
    "get_plugin",
    "get_plugin_config",
    "AuthFnHookContext",
    "AuthFnHooks",
    "AuthFnPlugin",
    "AuthFnPluginRuntimeContext",
    "ApiKey",
    "ApiKeyCreate",
    "ApiKeyResponse",
    "ApiKeySanitized",
    "ApiKeySession",
    "AuthFnSession",
    "AuthFnError",
    "AuthFnSchemaConflictError",
    "ApiKeyRevokedError",
    "ConfigError",
    "ConflictError",
    "CsrfInvalidError",
    "ValidationError",
    "InvalidCredentialsError",
    "ExpiredCredentialsError",
    "InternalError",
    "DeliveryFailedError",
    "EmailNotVerifiedError",
    "OtpInvalidError",
    "OtpExpiredError",
    "OtpReplayedError",
    "OAuthCallbackInvalidError",
    "OAuthProviderUnsupportedError",
    "OAuthStateInvalidError",
    "OAuthStateReplayedError",
    "PluginAbortedError",
    "RateLimitedError",
    "RedirectUriDisallowedError",
    "PlacementContextInvalidError",
    "PlacementDirectoryUnavailableError",
    "PlacementMovingError",
    "RegionMismatchError",
    "RegionNotFoundError",
    "RoutingAssertionInvalidError",
    "RoutingCellUnavailableError",
    "SessionExpiredError",
    "SessionRevokedError",
    "TwoFactorRequiredError",
    "TwoFactorInvalidCodeError",
    "UnauthorizedError",
    "NotFoundError",
    "NotImplementedAuthError",
    "authfn_password_plugin",
    "authfn_email_otp_plugin",
    "authfn_social_oauth_plugin",
    "authfn_api_key_plugin",
    "authfn_two_factor_plugin",
    "authfn_multi_region_plugin",
    "get_schema",
]


def __getattr__(name: str) -> object:
    if name in {"SocialOAuthPluginConfig", "SocialOAuthService", "SocialProviderConfig"}:
        from .plugins.social_oauth import (
            SocialOAuthPluginConfig,
            SocialOAuthService,
            SocialProviderConfig,
        )

        values = {
            "SocialOAuthPluginConfig": SocialOAuthPluginConfig,
            "SocialOAuthService": SocialOAuthService,
            "SocialProviderConfig": SocialProviderConfig,
        }
        return values[name]
    raise AttributeError(name)
